/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function convertBuffer(buffer: Buffer, optionsJson?: string | undefined | null): string

export declare function convertFile(path: string, optionsJson?: string | undefined | null): string

export declare function explain(code: string): string

export declare function inspectBuffer(buffer: Buffer): string

export declare function inspectFile(path: string): string

export declare function runtimeSource(): string

export declare function validateOutput(path: string, optionsJson?: string | undefined | null): string
